name: Tests
on: [push, pull_request]
env:
  CI: true

jobs:
  run:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: [14, 16]
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install npm dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run jest tests
        run: npm run jest -- --runInBand
        if: "!(startsWith(matrix.os, 'ubuntu') && matrix.node == 10)"

      - name: Run jest tests with coverage
        run: npm run jest -- --runInBand --coverage
        if: startsWith(matrix.os, 'ubuntu') && matrix.node == 10
